name: Create PR

on:
  release:
    types: [published]

jobs:
  create-pr:
    name: Create PR
    runs-on: ubuntu-latest
    steps:
      - name: Test
        run: |
          echo "hello world"
      - name: Checkout to actions-pr-test-1
        uses: actions/checkout@v2
        with:
          repository: tatane616/actions-pr-test-1

      - name: Create PR
        env: DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
        run: |
          ls
          echo "$GITHUB_IO_REPO_DEPLOY_KEY" > ~/deploy_key.pem
          chmod 600 ~/deploy_key.pem