name: Create PR

on:
  push:
    branches: [master]

jobs:
  create-pr:
    name: Create PR
    runs-on: ubuntu-latest
    steps:
      - name: Checkout to actions-pr-test-1
        uses: actions/checkout@v2
        with:
          repository: tatane616/actions-pr-test-1

      - name: Set git config
        env:
          DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
        run: |
          ls
          echo "$DEPLOY_KEY" > ~/deploy_key.pem
          chmod 600 ~/deploy_key.pem
          git config --global user.email "tatane616@gmail.com"
          git config --global user.name "tatane"
          git config remote.origin.url "git@github.com:tatane616/actions-pr-test-1.git"
          git checkout master
      
      - name: Create PR
        env:
          GIT_SSH_COMMAND: ssh -i ~/deploy_key.pem -o StrictHostKeyChecking=no -F /dev/null
        run: |
          ls
          date >| hoge.txt
          git add .
          git commit -m "commit by actions"
          git pull
          